### ISSUE TITLE
Opening the page in different monitors gives different results

### ISSUE THREAD

**Issue by noe** [ilkkapeltola/thumbmarkjs#3]
Steps to reproduce:
1. Open https://www.thumbmarkjs.com/ in a browser window.
2. Open https://www.thumbmarkjs.com/ in a browser window that is in a different screen from the previous one (e.g. laptop built-in screen and external screen). The fingerprint is different than in the previous step.

**Comment by ilkkapeltola** [comment]
And you were using the latest v0.11.0?
I can't reproduce right away. Which browser are you @noe using?

**Comment by noe** [comment]
I was using your demo page. I'm on Chrome under MacOS, both windows on normal (non-incognito) mode, user agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36".

The differences in the JSONs are:
* "elapsed" property inside "audio", "canvas", "fonts", ... On the laptop built-in screen it's generally half the value on the external screen.
* The lists inside "screen.value.mediaMatches" are quite different.

**Comment by ilkkapeltola** [comment]
Thanks for the patience @noe :)

The elapsed values are not considered in the fingerprint anyway. They're just milliseconds it took to calculate that particular component. 

But mediaMatches are different... that's interesting. And the audio, canvas and fonts take significantly longer on the external screen to calculate. That feels odd. Surely they would be running on the same chip, similar performance.

Sadly, I found your user agent from the logs only once. Not sure why the other fingerprint didn't get logged.

If you can indulge me again at some point, what I could find useful to debug is the following:
- The external screen: it's just a regular screen? Takes an HDMI signal or something? Or is it a wireless smart screen? Because of the delay differences, I'm wondering if it can be running some processing on it, but a regular screen shouldn't. It would need to be some fancy thing 😄
- If you can check the two fingerprints (it should be just 6 characters now). I'll see if I can find them both and see what's happening.
- If you can copy-paste the mediaMatches results. I should have them logged if I get the two fingerprints though. Unless your browser is blocking my logging for some reason on either screen. Not sure why this would happen.

**Comment by noe** [comment]
> The external screen: it's just a regular screen? Takes an HDMI signal or something? Or is it a wireless smart screen? Because of the delay differences, I'm wondering if it can be running some processing on it, but a regular screen shouldn't. It would need to be some fancy thing 😄

Yes, normal external HP screen, with a usb-C to HDMI adapter.

> If you can check the two fingerprints (it should be just 6 characters now). I'll see if I can find them both and see what's happening.

Fingerprints: itxh0y in the built-in screen, l4p9z2 in the external monitor.

> If you can copy-paste the mediaMatches results. I should have them logged if I get the two fingerprints though. Unless your browser is blocking my logging for some reason on either screen. Not sure why this would happen.

mediaMatches of the built-in screen:

```json
"mediaMatches": [
        "prefers-contrast: no-preference",
        "color-gamut: p3",
        "color-gamut: srgb",
        "dynamic-range: standard",
        "any-hover: hover",
        "any-pointer: fine",
        "pointer: fine",
        "hover: hover",
        "update: fast",
        "overflow-block: scroll",
        "overflow-inline: scroll",
        "color: 8",
        "prefers-reduced-motion: no-preference",
        "prefers-reduced-transparency: no-preference",
        "grid: 0",
        "scripting: enabled",
        "forced-colors: none",
        "display-mode: browser",
        "prefers-color-scheme: light"
      ]
```

mediaMatches of the external screen:

```json
"mediaMatches": [
        "prefers-contrast: no-preference",
        "color-gamut: srgb",
        "dynamic-range: standard",
        "any-hover: hover",
        "any-pointer: fine",
        "pointer: fine",
        "hover: hover",
        "update: fast",
        "overflow-block: scroll",
        "overflow-inline: scroll",
        "color: 8",
        "prefers-reduced-motion: no-preference",
        "prefers-reduced-transparency: no-preference",
        "grid: 0",
        "scripting: enabled",
        "forced-colors: none",
        "display-mode: browser",
        "prefers-color-scheme: light"
      ]
```

**Comment by noe** [comment]
I confirm that it works, for Chrome and for Safari. Also the same fingerprint in incognito mode.

By the way, I would like to suggest a more permissible license that allows thumbmarkjs to be used in contexts where the GPL is not an option. This is the reason I am not using this library.

**Comment by ilkkapeltola** [comment]
@noe I didn't think too much about licenses. Changed this to MIT now. Hope that works for your use case?

**Comment by noe** [comment]
Thanks! I installed it successfully in my Next.js project with npm with `npm i git+https://github.com/ilkkapeltola/thumbmarkjs` but it seems I cannot import it from typescript. Is thumbmarkjs not meant to be used like that?

**Comment by ilkkapeltola** [comment]
I'll open a new feature request.
